# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitledMain2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sqlite3

from PyQt5.QtCore import QStringListModel

import scr.error as error
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import QApplication, QMainWindow
import sys
from scr.mkdir import file


class Ui_MainWindow(object):
    def __init__(self):
        self.str1 = None
        self.list1 = []
        self.text = None
        self.pathFile = os.path.expanduser("~")
        self.id = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 120, 151, 351))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 170, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 80, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 20, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(230, 130, 451, 351))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.textBrowser = QtWidgets.QTextBrowser(self.page)
        self.textBrowser.setGeometry(QtCore.QRect(70, 80, 80, 40))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.page)
        self.textBrowser_2.setGeometry(QtCore.QRect(210, 80, 80, 40))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.page)
        self.textBrowser_3.setGeometry(QtCore.QRect(360, 80, 80, 40))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.page)
        self.textBrowser_4.setGeometry(QtCore.QRect(120, 140, 300, 40))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(10, 230, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")

        # self.plainTextEdit = QtWidgets.QTextBrowser(self.page_2)
        # self.plainTextEdit.setGeometry(QtCore.QRect(110, 70, 301, 221))
        # self.plainTextEdit.setObjectName("plainTextEdit")
        #
        self.listView = QtWidgets.QListView(self.page_2)
        self.listView.setGeometry(QtCore.QRect(110, 70, 301, 221))
        self.listView.setObjectName("listView")
        self.slm = QStringListModel()


        """
                self.plainTextEdit = QtWidgets.QPlainTextEdit(self.page_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(110, 70, 301, 221))
        self.plainTextEdit.setObjectName("plainTextEdit")"""
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.page)
        self.textBrowser_6.setGeometry(QtCore.QRect(120, 20, 300, 40))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.widget = QtWidgets.QWidget(self.page)
        self.widget.setGeometry(QtCore.QRect(10, 80, 431, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.textBrowser_2.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.textBrowser.raise_()
        self.textBrowser_3.raise_()
        self.label_5.raise_()
        self.textBrowser_4.raise_()
        self.label_6.raise_()

        self.label_7.raise_()
        self.textBrowser_6.raise_()
        self.stackedWidget.addWidget(self.page)

        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.page_2)
        self.textBrowser_7.setGeometry(QtCore.QRect(110, 10, 300, 40))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        """# self.textBrowser_5 = QtWidgets.QTextBrowser(self.page)
        # self.textBrowser_5.setGeometry(QtCore.QRect(120, 190, 300, 161))
        # self.textBrowser_5.setObjectName("textBrowser_5")"""
        self.textBrowser_5 = QtWidgets.QPlainTextEdit(self.page)
        self.textBrowser_5.setGeometry(QtCore.QRect(120, 190, 300, 161))
        self.textBrowser_5.setObjectName("textBrowser_5")

        self.pushButton_4 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_4.setGeometry(QtCore.QRect(320, 300, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.textBrowser_5.raise_()
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.stackedWidget.addWidget(self.page_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(630, 490, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton_1.clicked.connect(lambda: self.btn1_fun())
        self.pushButton_2.clicked.connect(lambda: self.btn2_fun())
        self.pushButton.clicked.connect(lambda: self.btn3_fun())
        self.pushButton_4.clicked.connect(lambda: self.btn4_fun())
        self.listView.clicked.connect(self.delaFile)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "小简科技"))
        self.groupBox.setTitle(_translate("MainWindow", "功能"))
        self.pushButton_2.setText(_translate("MainWindow", "写病历"))
        self.pushButton_1.setText(_translate("MainWindow", "查看病人信息"))
        self.label.setText(_translate("MainWindow", "医生服务系统"))
        self.label_5.setText(_translate("MainWindow", "身份证号："))
        self.label_6.setText(_translate("MainWindow", "写病历："))
        self.label_7.setText(_translate("MainWindow", "病历号："))
        self.label_2.setText(_translate("MainWindow", "姓名："))
        self.label_4.setText(_translate("MainWindow", "性别："))
        self.label_3.setText(_translate("MainWindow", "年龄："))
        self.label_8.setText(_translate("MainWindow", "病历号："))
        self.label_9.setText(_translate("MainWindow", "选择药品："))
        self.pushButton_4.setText(_translate("MainWindow", "提交"))
        self.pushButton.setText(_translate("MainWindow", "叫号"))

    def btn1_fun(self):
        self.stackedWidget.setCurrentIndex(0)

    def btn2_fun(self):
        self.stackedWidget.setCurrentIndex(1)

    def delaFile(self, qModelIndex):
        self.str1 = self.list1[qModelIndex.row()]

    def btn3_fun(self):
        self.textBrowser_6.clear()
        self.textBrowser.clear()
        self.textBrowser_2.clear()
        self.textBrowser_3.clear()
        self.textBrowser_4.clear()
        self.textBrowser_5.clear()
        self.textBrowser_7.clear()
        self.list1.clear()
        # self.plainTextEdit.clear()
        try:
            conn = sqlite3.connect(rf"{self.pathFile}\Jian\drug.db")
            c = conn.cursor()
            sun = c.execute("select NAME, NUM from JIAN ")

            for i in sun:
                self.list1.append(i[0] + "  " + i[1])
            self.slm.setStringList(self.list1)
            self.listView.setModel(self.slm)
            c.close()

            conn = sqlite3.connect(rf"{self.pathFile}\Jian\hospitaNum.db")
            c = conn.cursor()
            sun = c.execute(
                "select ID, NUM from JIAN ")
            for i in sun:
                conn.commit()
                c.execute("DELETE from JIAN where ID ='%s';" % i[0])
                conn.commit()
                c.close()
                break

            conn = sqlite3.connect(rf"{self.pathFile}\Jian\hospitaFile.db")
            c = conn.cursor()
            li = c.execute("select * from JIAN")
            list1 = li.fetchone()
            conn.commit()
            c.close()
            self.id = list1[0]
            self.textBrowser_6.append(list1[0])
            self.textBrowser.append(list1[1])
            self.textBrowser_2.append(list1[3])
            self.textBrowser_3.append(list1[2])
            self.textBrowser_4.append(list1[4])
            # self.textBrowser_5.append(list1[5])
            self.textBrowser_7.append(list1[0])


        except Exception:
            error.Win().show_message("提示", "没有病人")

    def btn4_fun(self):
        try:
            self.slm.setStringList(self.list1)
            self.listView.setModel(self.slm)
            self.text = self.textBrowser_5.toPlainText()
            conn = sqlite3.connect(rf"{self.pathFile}\Jian\hospitaFile.db")
            c = conn.cursor()
            sql = """UPDATE JIAN set BINLI = '%s' where  ID = '%s'""" % (self.text, self.id)
            c.execute(sql)
            conn.commit()
            # self.textBrowser_5.append(str1)
            # self.textBrowser_5.clear()
            li = c.execute("select * from JIAN")
            list1 = li.fetchone()
            c.execute("DELETE from JIAN where ID ='%s';" % list1[0])
            conn.commit()
            c.close()

            conn0 = sqlite3.connect(rf"{self.pathFile}\Jian\hospitaFileWc.db")
            c0 = conn0.cursor()
            sql = '''INSERT INTO JIAN (ID, NAME,AGE, SEX, USERID, KESI, BINLI, YP) VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s','%s')''' % (
                list1[0], list1[1], list1[2], list1[3], list1[4], list1[5], self.text, self.str1)
            c0.execute(sql)
            conn0.commit()
            conn0.close()
            error.Win().show_message("提示", "提交成功")
        except Exception as f:
            pass


if __name__ == '__main__':
    file()
    app = QApplication(sys.argv)
    m = QMainWindow()
    # 设置窗口尺寸
    Ui_MainWindow().setupUi(m)
    # 加载控件
    m.show()
    sys.exit(app.exec_())